- hosts: localhost
  become: true
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      tags:
        - update
  vars:
    user: "{{ansible_user_id}}"
  tasks:
    - include: ./tasks/zsh.yml
    - include: ./tasks/starship.yml
    - include: ./tasks/node.yml
