- hosts: localhost
  become: true
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      tags:
        - update
  vars:
    user: "{{ansible_user_id}}"
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - include: ./tasks/ssh.yml
    - include: ./tasks/zsh.yml
    - include: ./tasks/starship.yml
    - include: ./tasks/node.yml

